// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnaNsWxBoNif0Hm7Pf2xsQ1nQyad6lYng',
    appId: '1:72794748130:web:218d11c5dd480817cadabb',
    messagingSenderId: '72794748130',
    projectId: 'mitengajjar0',
    authDomain: 'mitengajjar0.firebaseapp.com',
    databaseURL: 'https://mitengajjar0.firebaseio.com',
    storageBucket: 'mitengajjar0.appspot.com',
    measurementId: 'G-RM7FYDDVEY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJAEH2z_zELc6klBRQ-hobmLO2B5H0RVQ',
    appId: '1:72794748130:android:54d8423a75385fb7cadabb',
    messagingSenderId: '72794748130',
    projectId: 'mitengajjar0',
    databaseURL: 'https://mitengajjar0.firebaseio.com',
    storageBucket: 'mitengajjar0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdtlKtyC1uyzpQyPDyhyxCoDwQv-WUBdE',
    appId: '1:72794748130:ios:ca8a76ad6f1484eccadabb',
    messagingSenderId: '72794748130',
    projectId: 'mitengajjar0',
    databaseURL: 'https://mitengajjar0.firebaseio.com',
    storageBucket: 'mitengajjar0.appspot.com',
    iosClientId: '72794748130-shei43jnmcejr2beuok95a9advd8doef.apps.googleusercontent.com',
    iosBundleId: 'com.example.fluttercounter',
  );
}
